/**
 * demopb/demo.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.GatewayMessageRequest
import io.swagger.client.model.GatewayMessageResponse
import io.swagger.client.model.RuntimeError
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object MessageServiceApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : GatewayMessageResponse (A successful response.)
   *   code 0 : RuntimeError (An unexpected error response)
   * 
   * @param body 
   */
  def messageServiceEcho(body: GatewayMessageRequest): ApiRequest[GatewayMessageResponse] =
    ApiRequest[GatewayMessageResponse](ApiMethods.POST, "https://localhost", "/v1/example/echo", "application/json")
      .withBody(body)
      .withSuccessResponse[GatewayMessageResponse](200)
      .withDefaultErrorResponse[RuntimeError]
      

}

